const menuBtn=document.getElementById('menu-btn');const nav=document.getElementById('primary-nav');menuBtn.addEventListener('click',()=>{const on=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(on));menuBtn.setAttribute('aria-label',on?'Close navigation':'Open navigation')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -35px 0px'});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
let scheduled=false;function updateScroll(){const h=document.documentElement;const pct=100*h.scrollTop/Math.max(h.scrollHeight-h.clientHeight,1);document.getElementById('scroll-progress').style.width=pct+'%';document.getElementById('header').classList.toggle('scrolled',h.scrollTop>20);scheduled=false}window.addEventListener('scroll',()=>{if(!scheduled){requestAnimationFrame(updateScroll);scheduled=true}},{passive:true});updateScroll();
const sections=document.querySelectorAll('main section[id]');const anchors=[...nav.querySelectorAll('a')];const sectionObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){anchors.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-30% 0px -55% 0px'});sections.forEach(s=>sectionObserver.observe(s));

// Application UI showcase
const shots=[{"name": "Dashboard", "desc": "Overview of cases and research workflows", "src": "assets/app-1.webp"}, {"name": "IoT Monitoring", "desc": "ESP32 vital-sign monitoring interface", "src": "assets/app-2.webp"}, {"name": "Patient Risk", "desc": "Clinical intake and baseline screening", "src": "assets/app-3.webp"}, {"name": "Cardiac Analysis", "desc": "ECG output and pathway review", "src": "assets/app-4.webp"}, {"name": "Gastric Support", "desc": "AI-guided treatment review interface", "src": "assets/app-5.webp"}, {"name": "Angiogram Analysis", "desc": "Coronary vessel mapping and stenosis annotation", "src": "assets/app-6.webp"}];
let activeShot=0;function setShot(i){activeShot=(i+shots.length)%shots.length;let s=shots[activeShot];document.getElementById('showcase-active').src=s.src;document.getElementById('showcase-active').alt=s.name+' interface preview';document.getElementById('showcase-title').textContent=s.name;document.getElementById('showcase-desc').textContent=s.desc;document.querySelector('.shot-count').textContent=String(activeShot+1).padStart(2,'0')+' / 06';document.querySelectorAll('.shot-thumb').forEach((b,j)=>{b.classList.toggle('selected',j===activeShot);b.setAttribute('aria-pressed',String(j===activeShot))});}
document.getElementById('shot-prev').addEventListener('click',()=>setShot(activeShot-1));document.getElementById('shot-next').addEventListener('click',()=>setShot(activeShot+1));document.querySelectorAll('.shot-thumb').forEach((b,i)=>b.addEventListener('click',()=>setShot(i)));
// Real embedded PDF viewer
const researchFiles=[{"name": "Proposal · Baseline Risk", "url": "documents/Proposal_Peiris.pdf"}, {"name": "Proposal · Cardiac", "url": "documents/Proposal_Maheesha.pdf"}, {"name": "Proposal · Angiogram", "url": "documents/Proposal_Wijewardhana.pdf"}, {"name": "Proposal · Gastric", "url": "documents/Proposal_Jayalath.pdf"}, {"name": "Project Proposal Slides", "url": "presentations/Proposal-Presentation.pdf"}, {"name": "Progress Presentation 2", "url": "presentations/PP2-Presentation.pdf"}];
document.querySelectorAll('.library-item').forEach((b,i)=>b.addEventListener('click',()=>{const file=researchFiles[i];document.getElementById('pdf-frame').src=file.url+'#toolbar=1&navpanes=0&view=FitH';document.getElementById('pdf-name').textContent=file.name;document.getElementById('pdf-download').href=file.url;document.getElementById('pdf-newtab').href=file.url;document.querySelectorAll('.library-item').forEach((x,j)=>{x.classList.toggle('current',j===i);x.setAttribute('aria-pressed',String(j===i))});}));
// Rich-but-respectful visual feedback
if(window.matchMedia('(pointer:fine) and (prefers-reduced-motion:no-preference)').matches){document.querySelectorAll('.module,.person-card,.supervisor-card').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.setProperty('--mx',((e.clientX-r.left)/r.width*100)+'%');card.style.setProperty('--my',((e.clientY-r.top)/r.height*100)+'%')});});}
